### ISSUE TITLE
[Bug]  0 * * * *  execute every minute

### ISSUE THREAD

**Issue by Geolim4** [synolia/SyliusSchedulerCommandPlugin#82] opened 2023-05-25 14:58 UTC
**Describe the bug**
I have set a task that would normally execute every hours: ` 0 * * * * `

Except it runs every minutes if I look at the history of scheduled commands ?

**To Reproduce**
Setup a task ` 0 * * * * ` and go to admin/scheduled-commands/

**Expected behavior**
Run every hours at m + 0.

**Screenshots**
![Capture d’écran de 2023-05-25 16-57-37](https://github.com/synolia/SyliusSchedulerCommandPlugin/assets/1332071/f155a34e-6129-4364-bfe7-d217da1fe9ba)
![Capture d’écran de 2023-05-25 16-57-19](https://github.com/synolia/SyliusSchedulerCommandPlugin/assets/1332071/d528949f-b059-4078-9aed-4bb8626582c1)

**Additional context**
N/A

**Comment by oallain** [comment] 2023-05-27 09:55
Hello @Geolim4 ,

We apologize for the inconvenience.
We have detected that the problem is due to the "Execute immediately" feature. This remains activated all the time, so the command runs in a loop.
We're going to fix this asap, but in the meantime, I'd advise you to deactivate it to get the desired effect.

Regards

**Comment by oallain** [comment] 2023-05-30 09:39
Hello @Geolim4 

Issue fixed in [v3.4.2](https://github.com/synolia/SyliusSchedulerCommandPlugin/releases/tag/v3.4.2)

Regards

**Closed by oallain** 2023-05-30 09:39 UTC
Labels: bug

**Comment by Geolim4** [comment] 2023-05-30 12:16
Wonderful, thank you very much !
